version: '3.9'
services:
  db:
    image: 'mysql:8.0'
    cap_add:
      - SYS_NICE
    restart: 'always'
    environment:
      - MYSQL_DATABASE=hackpsu-local
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./db/local/data:/var/lib/mysql
      - ./db/local/init.sql:/docker-entrypoint-initdb.d/init.sql
