name: Nest App Build Check

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
      - production
  pull_request:
    branches-ignore:
      - main
      - production
  workflow_dispatch:

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'


      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build the Nest Application
        run: yarn build
