name: Nest App Build Check

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
      - production
  pull_request:
    branches-ignore:
      - main
      - production
  workflow_dispatch:

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: yarn install

      - name: Build the Nest Application
        run: yarn build
