name: Deploy Production API

on:
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE: ${{ secrets.GCP_PRODUCTION_SERVICE_NAME }}
      IMAGE_NAME: us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_PRODUCTION_SERVICE_NAME }}/api-v3:${{ github.sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_PRODUCTION_SA_KEY }}
        
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authorize Docker Push
      run: gcloud auth configure-docker us-east4-docker.pkg.dev --quiet
      
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}
        
    - name: Deploy Cloud Run Service
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --region "us-east4" \
          --image ${{ env.IMAGE_NAME }} \
          --platform "managed" \
          --quiet
