name: Deploy Staging API

on:
  push:
    branches:
    - dev
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE: ${{ secrets.GCP_STAGING_SERVICE_NAME }}
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_STAGING_APP_NAME }}:${{ github.sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_STAGING_SA_KEY }}
        
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authorize Docker Push
      run: gcloud auth configure-docker --quiet
      
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}
        
    - name: Deploy Cloud Run Service
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --region "us-central1" \
          --image ${{ env.IMAGE_NAME }} \
          --platform "managed" \
          --quiet
      
      
        
      
  
    
