name: Deploy Staging API

permissions:
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE: ${{ secrets.GCP_STAGING_SERVICE_NAME }}
      IMAGE_NAME: us-east4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-v3/${{ secrets.GCP_STAGING_SERVICE_NAME }}:${{ github.sha }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0

    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_DEPLOYER_SA_KEY }}

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authorize Docker Push
      run: gcloud auth configure-docker us-east4-docker.pkg.dev --quiet

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6.18.0
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}

    - name: Deploy Cloud Run Service
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --region "us-east4" \
          --image ${{ env.IMAGE_NAME }} \
          --platform "managed" \
          --quiet
